development:
  clients:
    default:
      database: proudly_development
      hosts:
        - db:27017

test:
  clients:
    default:
      database: proudly_test
      hosts:
        - db:27017

fake:
  clients:
    default:
      database: proudly_fake
      hosts:
        - db:27017

production:
  clients:
    default:
      uri: <%= ENV["DATABASE_URL"] %>
