development:
  clients:
    default:
      database: kicker_development
      hosts:
        - db:27017

test:
  clients:
    default:
      database: kicker_test
      hosts:
        - db:27017

fake:
  clients:
    default:
      database: kicker_fake
      hosts:
        - db:27017

production:
  clients:
    default:
      uri: <%= ENV["DATABASE_URL"] %>
